---
- name: Apply role ceph-iscsigw
  gather_facts: false
  hosts: ceph-iscsigw
  become: true
  roles:
    - ceph-defaults
    - ceph-facts
    - ceph-handler
    - ceph-docker-common
    - ceph-config
    - ceph-iscsi-gw
